In [15]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.sql import text
import pymysql , subprocess , time
from sshtunnel import SSHTunnelForwarder
from sqlalchemy.exc import SQLAlchemyError
import settings

# 現在の作業ディレクトリの絶対パスを取得
import os
current_directory = os.getcwd()

# SSH接続情報
ssh_host = settings.SSH_HOST
ssh_port = settings.SSH_PORT  # デフォルトのSSHポート
ssh_user = settings.SSH_USER
ssh_key = current_directory + settings.SSH_KEY
print(ssh_host , ssh_port , ssh_user , ssh_key)

#port
local_port = 3307  # 任意のローカルポート
remote_port = 3306  # リモートMySQLサーバーのポート

# データベースの接続情報を設定
db_user = settings.DB_USER
db_password = settings.DB_PASSWORD
db_host = settings.DB_HOST
db_port = settings.DB_PORT
db_name = settings.DB_NAME

# 集計期間と取得サイト
collect_term=["2023-01-01" , "2024-12-31" ]
siteid_list=[443, 427 , 486 , 423 , 477 ,483 , 484 , 486]

# SSHトンネルを通す
def ssh_request():

    # SSHトンネルを作成
    ssh_command = [
        'ssh',
        '-i', ssh_key,
        '-L', f'{local_port}:127.0.0.1:{remote_port}',
        '-N',  # コマンドを実行せずにフォアグラウンドで実行
        '-f',  # バックグラウンドで実行
        '-p', str(ssh_port),
        f'{ssh_user}@{ssh_host}'
    ]

    # SSHトンネルの開始
    subprocess.run(ssh_command, check=True)
    print(f"SSH tunnel established on local port {local_port}")
    
    return


#DB　接続
def db_connect(db_user,db_password,local_port,db_name , site_id , startday , endday ):

    # データベース接続エンジンの作成
    engine = create_engine(f'mysql+pymysql://{db_user}:{db_password}@127.0.0.1:{local_port}/{db_name}')
    print("Database connection established.")

    #DB取得クエリ
    subscribe_query = text("""
            SELECT *
            FROM swan_analyze.analyze_ppv_all
            WHERE public_flg =1 AND site_id=:site_id AND date >=:start_day AND date <=:end_day
            """)
    
    #ここでエンジンを使用してデータベース操作を行います
    with engine.connect() as connection:
        result = connection.execute(subscribe_query , {"site_id":site_id , "start_day":startday , "end_day":endday})
        print(result)

        return result

        except SQLAlchemyError as e:
        print(f"An error occurred: {e}")

    
    

for s in siteid_list[5:6]:
    try:
        ssh_request()

        # SSHトンネルが確立されるまで少し待つ
        time.sleep(5)
        data = db_connect(db_user,db_password,local_port,db_name, s, collect_term[0] , collect_term[1] )


        # クエリの結果をPandas DataFrameに変換
        columns = data.keys()
        df = pd.DataFrame(result.fetchall(), columns=columns)

SyntaxError: incomplete input (711554982.py, line 91)

In [10]:
#エラーをチェック
print(df.isnull().sum())
print(len(df))

#DBデータをエキスポート
df.to_csv('ppv_history_origin.csv' ,  encoding='utf-8_sig')

site_id         0
carrier_id      0
member_id       0
uid             0
menuid          0
serviceid       0
start_date      0
end_date        0
payment_type    0
price           0
charge          0
public_flg      0
date            0
dtype: int64
8546

In [13]:
###### 加工データの作成

### データ生成

#全購入金額
df_total_price = df[['member_id' , 'price']].groupby('member_id').sum().reset_index()
#print(df_total_price)

#商品購入リスト
data_item = df.groupby('member_id')['menuid'].apply(list).reset_index()
#print(data_item)

#日付　リスト
data_inflow = df.groupby('member_id')['start_date'].apply(list).reset_index()
#print(data_inflow)

### 上記のデータを元データにマージ
df_add = pd.merge(df , df_total_price, on=['member_id'] , how='outer')
df_add = pd.merge(df_add , data_item, on=['member_id'] , how='outer')
df_add = pd.merge(df_add , data_inflow, on=['member_id'] , how='outer')

# 列名を変更
df_add = df_add.rename(columns={
    'price_y': 'total_sale',
    'menuid_y':'ppv_history' ,
    'start_date_y':'date_history' ,
    })


### 不要データの整理

#必要なカラムのみ抽出
column_list = ['site_id', 'member_id' , 'total_sale' , 'ppv_history', 'date_history'] #,'date_history' ]
df_add = df_add[column_list]

#重複データの削除
df_add = df_add.drop_duplicates(subset=['member_id'])

#6000円以上の人を抽出
df_add = df_add.query(' 6000 < total_sale ') 


print(df_add.tail(50) , len(df_add) )

#加工データをエキスポート
df_add.to_csv('ppv_processing.csv' ,  encoding='utf-8_sig')

      site_id                         member_id  total_sale  \
8033      483  ec6b9b8fab9ed3bf15cf5c97c0613546        9000
8037      483  ec919cb134c42ee153006fbab5fb532f       12600
8046      483  ecb6ae9dbcf2026a1f08c48c43d8409f       44200
8076      483  eddbf44d686cc3d85dd8de1b9c59e6a0        7000
8080      483  eddfcc7a417552ad272d908df8c0fb7d        8700
8085      483  edf7c4734ccd5259dec650ca22c73655       12800
8093      483  ee28b68c39945141903940344f62efe3        7500
8096      483  ee45c4175f4725e82ec3a0910217bff4        6200
8103      483  eeb8a81b319088272da0ba07e4d1dbeb        9500
8107      483  eec0fd4eb66f16f6a6d74f3840a69032        8500
8118      483  efb13c38f8666422530de370ea0423f5       13500
8124      483  f05b84f366256c82f2918f188692571b        8800
8132      483  f1111a0d83a65658692660f4ace1a288        7500
8146      483  f1d23b04ed414106925a0bea2aacd48b        6700
8149      483  f1fd60b994a4644a714236f4cda61739       37000
8163      483  f21b360535a7ac7a03edd75f0d7ed37d       64900
8197      483  f2ed1cd7817735e793374ecdcb8c3914       27800
8211      483  f302a2441d0431828e29038f2ee16e50       22200
8222      483  f35c54736f8e84e993c15956d030a986        9300
8233      483  f40873d574480d73104febaa50fc2397       19700
8248      483  f46ff3c50bccf34d0aa5ee5b5a628e92        9600
8252      483  f485ed50324a03c7ed9ae0a0e06b34d4        8500
8256      483  f48f8db8ece60cb08d5723b276a16d13       11600
8261      483  f4aa448d1f1f6c85bc62ed42e719b266        9800
8274      483  f56d1ee48d85fa4129d900b9ee19fea1       15500
8280      483  f571625ea24cc484df7fd9c7db032c07       11200
8286      483  f5783c713d9d054c17e9aa0da29bfaf0       15800
8296      483  f61adbd8f6ca3480c6af96af1bd0d887        7500
8300      483  f6230aed664288cc4e633dbdb4ed4fdb        6100
8317      483  f7ec5888bbbafcc8df756c8ecb87dc62       33000
8328      483  f7f4baf55a4dd602576de18b54049238       20000
8343      483  f8b17f8dd76e1b280e96146f29a0caef       19091
8349      483  f8d7232ff58d43155f99c8489302fb74       10000
8361      483  f9bca8c9f9171e19f5b569ab610e4cf5        8300
8365      483  f9ce304864db26d315f6ccc6ea10b37f       23000
8376      483  f9d77ce6974cda45886e44673f5d8c90       19400
8386      483  f9e01694b040f036eef7bbe6d97edd4c       85094
8428      483  fa3e0f5d462755624e63220b760ed9ef        8700
8435      483  fa946e71e4b2501f1fa09755d64b3fe9       10300
8439      483  fab5500acd1e96d4460b0982b566c932        7700
8451      483  fbc834b5112c9f42bb0cb8f102d9c09c       15600
8458      483  fbe837c9e10ddda8a0012d9198007938       13500
8468      483  fc8bfd856483ebede9584e6f845d5a5b        8500
8472      483  fcd4691659224e3df1a55832eb87a755       15700
8488      483  fd28429dfef89bd08e4045dc5183e616        6300
8493      483  fda0b45357a30d71ae36a01fdf223cd9       12700
8503      483  fde33885a5fe8086668cecea4733d9b9       10500
8509      483  fec4935721ba154e8148e6486efdf0b0       10700
8513      483  fed20770d38bad9bada2f095dac689d7       15700
8527      483  ff68b51e7d7fb864cdfa015bf01233d2       25800

                                            ppv_history  \
8033                                    [402, 002, 501]
8037                [057, 053, 015, 075, 020, 079, 052]
8046  [005, 006, 007, 002, 008, 029, 026, 031, 003, ...
8076                               [011, 856, 863, 085]
8080                               [003, 014, 010, 001]
8085                          [005, 413, 005, 112, 413]
8093                                         [003, 035]
8096                                         [055, 003]
8103                               [006, 002, 011, 009]
8107                                    [003, 005, 002]
8118                          [003, 800, 007, 004, 002]
8124                               [022, 041, 023, 002]
8132                                    [002, 009, 008]
8146                                    [586, 009, 015]
8149  [610, 402, 402, 036, 002, 009, 035, 402, 011, ...
8163  [002, 090, 005, 016, 009, 606, 016, 016, 092, ...
8197  [017, 016, 026, 002, 029, 024, 072, 005, 085, ...
8211      [009, 002, 055, 623, 403, 082, 864, 109, 107]
8222                               [002, 005, 018, 007]
8233           [005, 403, 002, 002, 009, 029, 534, 828]
8248                               [097, 617, 016, 002]
8252                                    [005, 403, 002]
8256                          [403, 026, 002, 008, 096]
8261                               [132, 131, 647, 002]
8274                     [002, 118, 003, 001, 001, 001]
8280                     [012, 001, 010, 014, 005, 008]
8286           [006, 531, 013, 041, 008, 026, 046, 025]
8296                                    [009, 586, 004]
8300                                    [001, 018, 016]
8317  [003, 403, 403, 413, 413, 403, 003, 403, 413, ...
8328           [055, 005, 009, 008, 002, 615, 016, 118]
8343                          [012, 001, 035, 039, 070]
8349                               [003, 002, 006, 008]
8361                               [005, 114, 113, 103]
8365  [002, 036, 046, 030, 052, 46, 30, 858, 015, 00...
8376           [872, 002, 622, 403, 047, 005, 095, 017]
8386  [002, 009, 008, 098, 016, 017, 101, 100, 055, ...
8428                               [005, 403, 014, 004]
8435                               [002, 009, 622, 095]
8439                               [015, 008, 005, 099]
8451                [010, 003, 007, 002, 021, 018, 073]
8458                     [005, 085, 079, 072, 606, 077]
8468                                    [002, 009, 624]
8472                [003, 005, 004, 070, 005, 014, 001]
8488                                    [009, 041, 024]
8493                          [003, 055, 009, 074, 863]
8503                               [002, 009, 008, 625]
8509                               [003, 005, 054, 055]
8513           [005, 132, 137, 017, 131, 130, 129, 121]
8527  [017, 802, 020, 055, 820, 018, 856, 074, 080, ...

                                           date_history
8033  [2024-11-22 06:10:43, 2024-11-22 23:21:52, 202...
8037  [2024-01-27 16:43:06, 2024-01-28 12:37:46, 202...
8046  [2024-04-01 01:09:28, 2024-04-01 01:22:56, 202...
8076  [2024-01-01 23:10:53, 2024-02-18 22:10:09, 202...
8080  [2024-01-05 22:34:49, 2024-01-06 01:53:44, 202...
8085  [2024-12-21 11:08:33, 2024-12-21 11:12:18, 202...
8093         [2024-01-25 22:07:29, 2024-01-25 23:38:20]
8096         [2024-11-05 12:51:20, 2024-11-06 16:27:05]
8103  [2024-01-01 22:23:23, 2024-01-01 22:31:55, 202...
8107  [2024-01-07 16:03:16, 2024-01-07 16:07:58, 202...
8118  [2024-01-07 01:27:52, 2024-01-08 01:34:58, 202...
8124  [2024-01-08 21:25:20, 2024-01-08 21:49:22, 202...
8132  [2024-06-17 14:20:09, 2024-06-17 14:40:55, 202...
8146  [2024-07-11 22:41:38, 2024-07-11 22:44:26, 202...
8149  [2024-01-01 10:43:06, 2024-01-01 10:46:06, 202...
8163  [2024-07-17 14:06:04, 2024-07-17 14:19:46, 202...
8197  [2024-06-20 06:37:01, 2024-06-20 22:34:58, 202...
8211  [2024-07-09 22:29:43, 2024-07-09 22:40:59, 202...
8222  [2024-02-05 12:41:26, 2024-02-28 02:27:47, 202...
8233  [2024-04-06 02:01:22, 2024-04-07 01:55:27, 202...
8248  [2024-08-02 23:47:09, 2024-08-02 23:50:51, 202...
8252  [2024-01-11 21:57:18, 2024-01-11 22:05:38, 202...
8256  [2024-02-23 13:30:23, 2024-03-03 21:26:13, 202...
8261  [2024-11-17 07:03:30, 2024-11-17 07:17:54, 202...
8274  [2024-10-23 18:57:51, 2024-10-23 19:03:51, 202...
8280  [2024-01-01 13:04:56, 2024-01-03 15:17:30, 202...
8286  [2024-01-03 23:30:52, 2024-01-04 05:51:47, 202...
8296  [2024-04-20 23:58:36, 2024-04-21 23:53:40, 202...
8300  [2024-08-09 16:04:13, 2024-08-10 01:50:31, 202...
8317  [2024-11-20 15:49:45, 2024-11-20 15:51:55, 202...
8328  [2024-08-11 23:20:08, 2024-08-12 06:09:19, 202...
8343  [2024-01-07 07:13:45, 2024-01-07 07:17:56, 202...
8349  [2024-01-10 21:43:09, 2024-01-10 22:58:00, 202...
8361  [2024-10-02 20:41:40, 2024-10-02 21:25:20, 202...
8365  [2024-01-03 17:17:32, 2024-01-14 15:48:16, 202...
8376  [2024-11-23 10:19:57, 2024-11-23 10:28:38, 202...
8386  [2024-08-03 12:00:56, 2024-08-03 12:16:29, 202...
8428  [2024-09-29 21:48:37, 2024-09-29 21:52:43, 202...
8435  [2024-07-19 21:57:56, 2024-07-19 22:06:34, 202...
8439  [2024-01-06 21:48:01, 2024-01-06 21:51:31, 202...
8451  [2024-01-02 23:07:07, 2024-01-02 23:07:27, 202...
8458  [2024-03-24 00:33:26, 2024-03-24 00:37:45, 202...
8468  [2024-12-12 01:58:42, 2024-12-12 02:02:20, 202...
8472  [2024-02-01 21:18:17, 2024-02-03 20:18:26, 202...
8488  [2024-01-02 18:41:55, 2024-01-05 20:14:08, 202...
8493  [2024-01-14 20:08:11, 2024-01-20 02:19:52, 202...
8503  [2024-07-25 00:04:47, 2024-07-25 00:31:01, 202...
8509  [2024-01-23 22:37:12, 2024-01-23 22:40:55, 202...
8513  [2024-12-05 01:38:14, 2024-12-05 02:08:27, 202...
8527  [2024-01-04 22:26:41, 2024-01-13 01:19:41, 202...   756

,site_id,carrier_id,member_id,uid,menuid,serviceid,start_date,end_date,payment_type,price,charge,public_flg,date
0,483,6,c1dace7fae7bc015acede89594470760,0001GJhyHQkVnWK0LfZpoXcG0MOVc,007,00073734512,2024-01-01 00:21:07,0000-00-00 00:00:00,1,2000,2000,1,2024-01-01
1,483,6,b0ea90aff78d1d0d72fea66af07f6380,0001GNBBkXR7rpU7mBuNorNDDHOZ4,014,00073734512,2024-01-01 00:43:49,0000-00-00 00:00:00,1,1200,1200,1,2024-01-01
2,483,6,e19c56f028800424e2b92a0fe3b0144d,0001GNtOnrRsmfa5m02XFEWiQNOaK,002,00073734512,2024-01-01 01:23:05,0000-00-00 00:00:00,1,3000,3000,1,2024-01-01
3,483,6,e19c56f028800424e2b92a0fe3b0144d,0001GNtOnrRsmfa5m02XFEWiQNOaK,009,00073734512,2024-01-01 01:34:27,0000-00-00 00:00:00,1,2500,2500,1,2024-01-01
4,483,6,421808c1273e07e304adc59ccf0461cc,0001GJq6Hdf0fVQ0Crg6P0jSNoObO,006,00073734512,2024-01-01 01:46:57,0000-00-00 00:00:00,1,2000,2000,1,2024-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8072,483,110,769443f13d0a4f398d9db0e0823b38a9,MKB_00057139,818,,2024-11-30 21:22:55,0000-00-00 00:00:00,2,1500,1500,1,2024-11-30
8073,483,110,769443f13d0a4f398d9db0e0823b38a9,MKB_00057139,606,,2024-11-30 21:35:27,0000-00-00 00:00:00,2,3000,3000,1,2024-11-30
8074,483,110,769443f13d0a4f398d9db0e0823b38a9,MKB_00057139,011,,2024-11-30 22:54:01,0000-00-00 00:00:00,2,2000,2000,1,2024-11-30
8075,483,110,65dddb6776f94d448073e3383bf66f6d,amzn1.account.AGVNB23XM35665YN7PRALN2ZMKUA,011,,2024-11-30 23:13:21,0000-00-00 00:00:00,6,2000,2000,1,2024-11-30
8076,483,110,38b7ff94ba64eb95dd9dae9ab5c60c11,member-000259192,141,,2024-11-30 23:51:17,0000-00-00 00:00:00,9,2600,2600,1,2024-11-30